### PR TITLE
Minor tense changes to the main readme

### PR DESCRIPTION
**Pull request by kluzny**
Also changed George to Gregor, and added a sentence to the security features.  I think often considering your attack surface ( amount of exposed code) should be more of a priority.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by irae** [comment]
@davglass looks like the YahooCLA bot is broken, people told me they could see the "valid" comment before they actually signed.

**Comment by irae** [comment]
Thank you very much for the fixes! We appreciate very much documentation contribution!

**Pull request merged**
