### PR TITLE
Added CSS support for mendel-deps with tests

### PR DESCRIPTION
**Pull request by stephanwlee**
TODO: Need to strip "@import" in outputted CSS file.

### CODE REVIEW

**Comment by irae** [comment]
😍 

OMG you did it! I'll review once time allows, I just wanted to say I love this! ❤️

**Comment by muralikr** [comment]
Any reason for merging this PR before review??

**Comment by stephanwlee** [comment]
Is there a policy against it?

**Comment by irae** [comment]
I had reviewed most of it and talked with him about architecture impact of it in the Slack #arch channels. We can always move back if needed. But this will be very interesting for community adoption for sure.

**Comment by muralikr** [comment]
We are in process of adding unit tests and more stability. We had many regressions because we are still lacking in these areas. Till we have proper build pipeline to validate our changes, it is better to have a thorough code review at least. Also, we are not in a race with a deadline. So, no harm in asking for reviews before merge.

**Comment by irae** [comment]
@muralikr please lets have a chat about testing. I have a few ideas on improving how we do it. Secondly. Merging to master is also the least of our problems. We are not pushing to NPM without thorough testing anyway, so let's not push contributors away, specially publicly about their mistakes.

**Pull request merged**
